# Default initial positions for macro's ros2_control fake system

initial_positions:
  frame_to_slede: 0
  shoulder_pan_joint: 0.0
  shoulder_lift_joint: -1.57
  elbow_joint: 0.0
  wrist_1_joint: -1.57
  wrist_2_joint: 0.0
  wrist_3_joint: 0.0