# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    slede_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

slede_controller:
  ros__parameters:
    joint: frame_to_slede
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_controller:
  ros__parameters:
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
robot_controller:
  ros__parameters:
    joints:
      - frame_to_slede
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity