<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="frame">
    <xacro:property name="frame_length" value="1" />
    <xacro:property name="frame_width" value="0.3" />
    <xacro:property name="frame_height" value="0.1125" />

    <material name="light_grey">
        <color rgba="0.8 0.8 0.8 1" />
    </material>
    
    <link name="base_link">
        <visual>
            <origin rpy="0 0 ${pi/2}" xyz="${frame_length/2} 0 0"/>
            <material name="light_grey"/>
            <geometry>
                <mesh filename="package://robo_inspecto_launch/meshes/frame.stl" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="${frame_length/2} 0 ${frame_height/2}"/>
            <geometry>
                <box size="${frame_length} ${frame_width} ${frame_height}" />
            </geometry>
        </collision>
    </link>
</robot>