<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="macro">
    <xacro:include filename="slede.urdf.xacro" />
    <xacro:include filename="frame.urdf.xacro" />

    <xacro:property name="robot_name" value="ur5" />

    <!-- import ur5e -->
    <xacro:include filename="$(find ur_description)/urdf/ur_macro.xacro" />

    <xacro:ur_robot
        name="ur"
        tf_prefix="ur_"
        parent="base_plate_link"
        joint_limits_parameters_file="$(find ur_description)/config/${robot_name}/joint_limits.yaml"
        kinematics_parameters_file="$(find ur_description)/config/${robot_name}/default_kinematics.yaml"
        physical_parameters_file="$(find ur_description)/config/${robot_name}/physical_parameters.yaml"
        visual_parameters_file="$(find ur_description)/config/${robot_name}/visual_parameters.yaml"
        script_filename="$(find ur_client_library)/resources/external_control.urscript"
        output_recipe_filename="$(find ur_robot_driver)/resources/rtde_output_recipe.txt"
        input_recipe_filename="$(find ur_robot_driver)/resources/rtde_input_recipe.txt"
        robot_ip="192.168.10.100"
        reverse_ip="192.168.132"
    ><origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:ur_robot>
    
    
    <!-- connect slede to frame -->
    <joint name="frame_to_slede" type="prismatic">
        <parent link="base_link" />
        <child link="base_plate_link" />
        <origin xyz="${plate_width/2} 0 ${frame_height+plate_thickness}" />
        <axis xyz="1 0 0" />
        <limit lower="0" upper="${frame_length - plate_width}" effort="100" velocity="0.5" />
    </joint>
</robot>